"################## VUNDLE BEGIN
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

Plugin 'severin-lemaignan/vim-minimap'
Plugin 'davidhalter/jedi-vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"################## VUNDLE END

"############## PERSONAL BEGIN
:syn on
:set tabstop=4
:set shiftwidth=4
:set expandtab
:set hlsearch
:set incsearch
:set number
:set cursorline
:set ruler

au BufRead,BufNewFile Jenkinsfile* set filetype=groovy
au BufRead,BufNewFile *.md set filetype=markdown
au BufRead,BufNewFile *.go set filetype=go
au BufRead,BufNewFile *.y*ml set tabstop=2 shiftwidth=2
au BufRead,BufNewFile *.py set foldmethod=indent

:cmap ,d :w !diff % -
:cmap ,p :0,$!yapf
:cmap ,m :w !mypy %

""remap escape for stupid touchbars
":imap ii <Esc> 

""open files from explore in previous split
let g:netrw_browse_split = 4

""enable pathogen(which if jedi is installed, starts it automatically
"execute pathogen#infect() 

""disable jedi
"let g:jedi#auto_initialization = 0

"" don't pop open autocomplete on by typing '.'
"let g:jedi#popup_on_dot = 0 

""can disable showing call signatures altogether
"let g:jedi#show_call_signatures = "1" 

"jedi sets this to 80, which i think is lame
:set textwidth=0 
"############## PERSONAL END
