"############## PERSONAL BEGIN
:syn on
:set tabstop=4
:set shiftwidth=4
:set expandtab
:set hlsearch
:set incsearch
:set number
:set cursorline
:set ruler

au BufRead,BufNewFile Jenkinsfile* set filetype=groovy
au BufRead,BufNewFile *.md set filetype=markdown
au BufRead,BufNewFile *.go set filetype=go
au BufRead,BufNewFile *.y*ml set tabstop=2 shiftwidth=2
au BufRead,BufNewFile *.py set foldmethod=indent

:cmap ,d :w !diff % -
:cmap ,p :0,$!yapf
:cmap ,m :w !mypy %
:cmap ,j :0,$!jq . 

""remap escape for stupid touchbars
":imap ii <Esc> 

""open files from explore in previous split
"let g:netrw_browse_split = 4

""enable pathogen(which if jedi is installed, starts it automatically
"execute pathogen#infect() 

""disable jedi
"let g:jedi#auto_initialization = 0

"" don't pop open autocomplete on by typing '.'
"let g:jedi#popup_on_dot = 0 

""can disable showing call signatures altogether
"let g:jedi#show_call_signatures = "1" 

"jedi sets this to 80, which i think is lame
:set textwidth=0 

"allow cursor to move to empty spaces, only padding them if edited
"set virtualedit=all
"############## PERSONAL END
