:syn on
:set tabstop=4
:set shiftwidth=4
:set expandtab
:set hlsearch
:set incsearch
:set number
:set cursorline

au BufRead,BufNewFile Jenkinsfile set filetype=groovy
au BufRead,BufNewFile *.md set filetype=markdown
au BufRead,BufNewFile *.go set filetype=go
au BufRead,BufNewFile *.y*ml set tabstop=2 shiftwidth=2

:cmap ,h :!html-beautify -f % -r
:cmap ,j :!js-beautify -f % -r
:cmap ,l :!jslint %
:cmap ,p :0,$!yapf
:cmap ,d :w !diff % -

:imap ii <Esc>

" netrw(Explore) opens files in previous window
"let g:netrw_browse_split = 4
